name: Clean and Sanitize CSV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  clean-csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas beautifulsoup4

    - name: Clean and sanitize CSV
      run: |
        python -c "
        import pandas as pd
        from bs4 import BeautifulSoup

        def clean_title(title):
            if isinstance(title, str):
                # Remove HTML tags using BeautifulSoup
                title = BeautifulSoup(title, 'html.parser').get_text()
                # Remove leading/trailing whitespace
                title = title.strip()
                return title
            elif isinstance(title, float):
                return str(title)
            else:
                return ''

        # Read the CSV file with UTF-8 encoding
        df = pd.read_csv('feed-data.csv', encoding='utf-8')

        # Clean and sanitize the 'Title' column
        df['Title'] = df['Title'].apply(clean_title)

        # Remove duplicate entries based on the 'Link' column
        df.drop_duplicates(subset='Link', keep='first', inplace=True)

        # Save the cleaned and sanitized data back to the CSV file with UTF-8 encoding
        df.to_csv('feed-data.csv', index=False, encoding='utf-8')
        "

    - name: Commit and push changes
      run: |
        git config --local user.email "${{ secrets.USER_EMAIL }}"
        git config --local user.name "${{ secrets.USER_NAME }}"
        git add feed-data.csv
        git commit -m "Clean and sanitize CSV data"
        git push